### ISSUE TITLE
Push notifications with webpush api?

### ISSUE THREAD

**Issue by pwFoo** [NaderIkladious/cockpit-push-notification#1]
Hi,

I'm searching for headless cms with push notification support. Started playing with Directus before. So no experience with cockpit.

Your module is using FCM / Google push notifications, but it would be awesome to have a device dependent solution!

Do you know webpush api?
https://github.com/web-push-libs/web-push-php

It works with the push service dependent on the device / browser without to force for example firefox users to use google push service.

Any change you would take a look into the web-push-php library to make your push notification plugin independent from google service?

**Comment by NaderIkladious** [comment]
Hello,

Thanks for your message.
At the time of writing the plugin, This library didn't cross my sight, but it looks promising.
But, unfortunately, there are no plans at the moment to have further development into this plugin.

Maybe in the future, But feel free to fork the plugin and implement it.

**Comment by pwFoo** [comment]
Hi @NaderIkladious,
did you stop using cockpit or just not need to develop / use the plugin anymore?

Or do you have switched to another (headless) cms? Would be nice to know because I need to decide which cms to use for that case. 

Directus was nice and worked fine, but I haven't found a push notification plugin for it. That's way I searched for headless cms with such a plugin :)
